### ISSUE TITLE
One question about the limit of cell count in partl analysis

### ISSUE THREAD

**Issue by thissbiscrazy** [jhausser/ParTI#1]
hello, I am doing partl analysis about the single cell gene expression data. When the cell count is too big, my computer cannot afford the    program. I want to ask about the upper bound of the cell count or gene count. Is it only depends on the internal memory of the computer or server, or depends on other things. Thank you very much.

**Comment by jhausser** [comment]
ParTI doesn't have a limit on the number of cells or data points. It depends on your computer and on whether your admin set software limits on memory usage.
